apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      env:
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
