apiVersion: v1
kind: Pod
metadata:
  name: docker-agent-pod # Pod 이름 명시적으로 설정
  labels:
    app: docker-agent
spec:
  containers:
    - name: docker
      image: docker:26.1.3 # Docker CLI 이미지 버전
      command:
        - cat # Pod이 종료되지 않도록 유지
      tty: true
      securityContext:
        privileged: true # Docker 데몬 접근을 위해 privileged 모드 활성화
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock # 호스트 Docker 소켓 마운트
        - name: jenkins-workspace
          mountPath: /home/jenkins/agent # Jenkins 워크스페이스 마운트
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
        type: Socket # Docker 소켓 파일
    - name: jenkins-workspace
      hostPath:
        path: /home/jenkins/agent # 호스트의 Jenkins 워크스페이스 경로
        type: DirectoryOrCreate # 경로가 없으면 자동 생성
