apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-with-docker
spec:
  containers:
  - name: jenkins-agent
    image: jenkins/inbound-agent:latest
    volumeMounts:
      - mountPath: "/home/jenkins/agent"
        name: workspace-volume
      - mountPath: /var/run/docker.sock
        name: docker-socket
  - name: docker
    image: docker:latest
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-socket
  volumes:
    - name: workspace-volume
      emptyDir: {}
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
  restartPolicy: Never
