apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    - name: docker
      image: docker:27.3.1
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock


# apiVersion: v1
# kind: Pod
# metadata:
#   name: docker-agent-pod
#   labels:
#     app: docker-agent
# spec:
#   containers:
#     - name: docker
#       image: docker:27.3.1
#       command:
#         - cat
#       tty: true
#       securityContext:
#         privileged: true
#       volumeMounts:
#         - name: dockersock
#           mountPath: /var/run/docker.sock
#         - name: workspace-volume
#           mountPath: /home/jenkins/agent  # 워크스페이스 경로 마운트
#   volumes:
#     - name: dockersock
#       hostPath:
#         path: /var/run/docker.sock
#         type: Socket
#     - name: workspace-volume
#       hostPath:
#         path: /home/jenkins/agent  # 호스트의 워크스페이스 경로
#         type: DirectoryOrCreate
