pipeline {
  agent {
    kubernetes {
      defaultContainer 'kaniko'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - "3600"
    volumeMounts:
    - name: harbor-creds
      mountPath: /kaniko/.docker
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  - name: jnlp
    image: jenkins/inbound-agent:latest
  volumes:
  - name: harbor-creds
    secret:
      secretName: harbor-creds
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: workspace-volume
    emptyDir: {}
"""
    }
  }

  environment {
    IMAGE_NAME = "harbor.locall:30004/jentest/nginx"
    IMAGE_TAG = "${BUILD_NUMBER}"
    FULL_IMAGE = "${IMAGE_NAME}:${IMAGE_TAG}"
  }

  stages {
    stage('Checkout') {
      steps {
        git credentialsId: 'github-token', url: 'https://github.com/hwseo0406/hwseo_site.git', branch: 'main'
      }
    }

    stage('Check Kaniko Config') {
      steps {
        container('kaniko') {
          sh 'cat /kaniko/.docker/config.json || echo "❌ config.json not found"'
        }
      }
    }

    stage('Build & Push with Kaniko') {
      steps {
        container('kaniko') {
          sh """
            /kaniko/executor \
              --context `pwd` \
              --dockerfile `pwd`/Dockerfile \
              --destination=${FULL_IMAGE} \
              --insecure \
              --skip-tls-verify
          """
        }
      }
    }

    stage('Update Manifest & Push') {
      steps {
        container('jnlp') {
          withCredentials([usernamePassword(credentialsId: 'hwseo github token', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
            script {
              def newImage = "${FULL_IMAGE}"
              sh """
                sed -i 's|image: .*|image: ${newImage}|' ./jentest/jentest-deployment.yaml
                cat ./jentest/jentest-deployment.yaml

                git config --global user.email "hse05078@gmail.com"
                git config --global user.name "hwseo0406"
                git remote set-url origin https://${GIT_USER}:${GIT_TOKEN}@github.com/hwseo0406/hwseo_site.git

                git add ./jentest/jentest-deployment.yaml
                git commit -m "Update image to ${newImage} [skip ci]" || echo "No changes to commit"
                git push origin main
              """
            }
          }
        }
      }
    }
  }

  post {
    success {
      echo "✅ 이미지 빌드 및 매니페스트 업데이트 성공: ${FULL_IMAGE}"
    }
    failure {
      echo "❌ 실패. 로그를 확인하세요."
    }
  }
}
